Collision Free Speed Model v3
PedestrianDynamics/jupedsim pull request #1432
Opened 2024-12-30 15:41 UTC by chraibi

In this PR, an enhanced version of the CFSM is implemented. 
It will be version 3 of the model.

2025-01-01 12:21 UTC, Ozaq reviewed
You should consider another name for this model. CFSMv3 implies a direct evolution on v2. I am not sure if this really is the case or if there is more novelty to it.

2025-01-06 18:39 UTC, chraibi commented
@xuqiancheng I think the model is ready for your review. Can you please check if the equations are implemented correctly according to the model?

We can not yet use the model though, due to lack of the python-API.

2025-01-07 08:51 UTC, xuqiancheng reviewed
I have checked the code, except for the function **BoundaryRepulsion**,  other equations of the AVM are implemented correctly.

2025-01-07 09:44 UTC, chraibi commented on libsimulator/src/AnticipationVelocityModel.cpp
> +    if (result_e0 < 0 && result_ei < 0) return Point(0, 0);
Thanks! I updated the implementation to check for both edges. See my last commit.

2025-01-07 09:45 UTC, chraibi commented on libsimulator/src/AnticipationVelocityModel.cpp
> +    const auto private_space = 0.5;
That was something I had in mind. But now, I remove it, since in this PR I want to have AVM without modifications.

2025-01-15 13:22 UTC, chraibi commented
@Ozaq I think most of the text in the first cell of the model-comparison-notebook, might be better placed in pedestrian_models/index.html.

What do you think? I would do it directly in this PR.

2025-01-15 19:24 UTC, Ozaq commented on CMakeLists.txt
> +project(JuPedSim VERSION 1.3.1 LANGUAGES CXX)
Please revert the version bump, 1.3.0 is still unreleased

2025-01-15 19:24 UTC, Ozaq commented on examples/example7_avm.py
> +    # exit_polygon = shapely.box(48, -2.5, 50, 2.5)  #
remove commented out code

2025-01-20 18:45 UTC, Ozaq requested changes

2025-01-20 18:45 UTC, Ozaq commented on libsimulator/src/AnticipationVelocityModel.cpp
> +    static std::mt19937 gen(42);
The seed needs to become a model parameter. Otherwise I think this will become a breaking change later on.

2025-01-22 09:44 UTC, Ozaq approved these changes

2025-01-22 22:00 UTC, Ozaq approved these changes

2025-01-22 22:01 UTC, merged